esphome:
  name: bt-proxy
  friendly_name: BT Proxy
  # Delay boot until WiFi is up to avoid BT+WiFi conflicts on startup
  # See: https://github.com/esphome/issues/issues/2941
  on_boot:
    priority: 250
    then:
      - wait_until:
          condition:
            wifi.connected:

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_esp32s3_btproxy

ota:
  - platform: esphome
    password: !secret ota_password_esp32s3_btproxy

wifi:
  ssid: !secret wifi_ssid_iot
  password: !secret wifi_password_iot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid_iot_fallback
    password: !secret wifi_password_iot_fallback

captive_portal:

# Enable logging
logger:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 350ms
    active: true

# BT proxy for other BLE devices — 1 slot reserved for the Inkbird direct connection
bluetooth_proxy:
  active: true
  connection_slots: 2

# Direct BLE connection to Inkbird IHT-2PB
# Add "ble_mac_address: XX:XX:XX:XX:XX:XX" to your secrets.yaml
# Find with: nRF Connect app, or check ESPHome logs for a device named "sps"
ble_client:
  - mac_address: !secret ble_mac_address
    id: inkbird_IHT_2PB_ble
    on_connect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Connected to Inkbird IHT-2PB");
            id(inkbird_IHT_2PB_connected).publish_state(true);
        - delay: 2s   # Wait for BLE stack to be fully ready before sending writes
        - button.press: inkbird_IHT_2PB_notification
    on_disconnect:
      then:
        - lambda: |-
            ESP_LOGD("ble_client_lambda", "Disconnected from Inkbird IHT-2PB");
            id(inkbird_IHT_2PB_connected).publish_state(false);

script:
  - id: activate_temperature_notifications
    then:
      - ble_client.ble_write:
          id: inkbird_IHT_2PB_ble
          service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ffe9-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0x19, 0x01, 0x00, 0x19]
      - ble_client.ble_write:
          id: inkbird_IHT_2PB_ble
          service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
          characteristic_uuid: 0000ffe4-0000-1000-8000-00805f9b34fb
          value: [0x55, 0xAA, 0x1A, 0x01, 0x00, 0x1A]
          # Note: "does not allow writing" error is expected here but notifications still work

switch:
  - platform: ble_client
    ble_client_id: inkbird_IHT_2PB_ble
    name: "Inkbird IHT-2PB enable"

button:
  - platform: restart
    name: "BT Proxy Restart"
    icon: "mdi:restart"
    entity_category: diagnostic

  - platform: template
    id: inkbird_IHT_2PB_notification
    name: "Inkbird IHT-2PB notification"
    on_press:
      - script.execute: activate_temperature_notifications

number:
  # Alarm target temperature sliders — changing the value sends a BLE write to the device.
  # Protocol: 55 AA <cmd> 04 <hi> <lo> FF FF <checksum>
  #   - Command byte: 0x0D = internal probe, 0x0E = probe 1 (external), 0x0F = probe 2 (external)
  #   - High alarm = value * 10 as big-endian uint16 (e.g. 124.0°C → 1240 → 0x04 0xD8)
  #   - Low alarm  = 0xFF 0xFF (disabled)
  #   - Checksum   = sum of all preceding bytes mod 256

  - platform: template
    name: "Inkbird internal probe alarm temperature"
    id: inkbird_IHT_2PB_alarm0
    icon: mdi:thermometer-alert
    unit_of_measurement: "°C"
    min_value: -40
    max_value: 300
    step: 0.5
    optimistic: true
    restore_value: true
    initial_value: 100
    on_value:
      then:
        - ble_client.ble_write:
            id: inkbird_IHT_2PB_ble
            service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
            characteristic_uuid: 0000ffe9-0000-1000-8000-00805f9b34fb
            value: !lambda |-
              int temp_int = (int)(x * 10);
              uint8_t hi = (temp_int >> 8) & 0xFF;
              uint8_t lo = temp_int & 0xFF;
              std::vector<uint8_t> payload = {0x55, 0xAA, 0x0D, 0x04, hi, lo, 0xFF, 0xFF};
              uint8_t checksum = 0;
              for (auto b : payload) checksum += b;
              payload.push_back(checksum);
              return payload;

  - platform: template
    name: "Inkbird probe 1 alarm temperature"
    id: inkbird_IHT_2PB_alarm1
    icon: mdi:thermometer-alert
    unit_of_measurement: "°C"
    min_value: -40
    max_value: 300
    step: 0.5
    optimistic: true
    restore_value: true
    initial_value: 100
    on_value:
      then:
        - ble_client.ble_write:
            id: inkbird_IHT_2PB_ble
            service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
            characteristic_uuid: 0000ffe9-0000-1000-8000-00805f9b34fb
            value: !lambda |-
              int temp_int = (int)(x * 10);
              uint8_t hi = (temp_int >> 8) & 0xFF;
              uint8_t lo = temp_int & 0xFF;
              std::vector<uint8_t> payload = {0x55, 0xAA, 0x0E, 0x04, hi, lo, 0xFF, 0xFF};
              uint8_t checksum = 0;
              for (auto b : payload) checksum += b;
              payload.push_back(checksum);
              return payload;

  - platform: template
    name: "Inkbird probe 2 alarm temperature"
    id: inkbird_IHT_2PB_alarm2
    icon: mdi:thermometer-alert
    unit_of_measurement: "°C"
    min_value: -40
    max_value: 300
    step: 0.5
    optimistic: true
    restore_value: true
    initial_value: 100
    on_value:
      then:
        - ble_client.ble_write:
            id: inkbird_IHT_2PB_ble
            service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
            characteristic_uuid: 0000ffe9-0000-1000-8000-00805f9b34fb
            value: !lambda |-
              int temp_int = (int)(x * 10);
              uint8_t hi = (temp_int >> 8) & 0xFF;
              uint8_t lo = temp_int & 0xFF;
              std::vector<uint8_t> payload = {0x55, 0xAA, 0x0F, 0x04, hi, lo, 0xFF, 0xFF};
              uint8_t checksum = 0;
              for (auto b : payload) checksum += b;
              payload.push_back(checksum);
              return payload;

binary_sensor:
  - platform: template
    name: "Inkbird IHT-2PB connected"
    id: inkbird_IHT_2PB_connected
    icon: mdi:bluetooth-connect

  - platform: template
    name: "Inkbird internal probe alarm"
    id: inkbird_IHT_2PB_alarm_state0
    icon: mdi:alarm-bell
    device_class: heat
    lambda: |-
      if (!id(inkbird_IHT_2PB_probe0).has_state()) return false;
      return id(inkbird_IHT_2PB_probe0).state >= id(inkbird_IHT_2PB_alarm0).state;

  - platform: template
    name: "Inkbird probe 1 alarm"
    id: inkbird_IHT_2PB_alarm_state1
    icon: mdi:alarm-bell
    device_class: heat
    lambda: |-
      if (!id(inkbird_IHT_2PB_probe1).has_state()) return false;
      return id(inkbird_IHT_2PB_probe1).state >= id(inkbird_IHT_2PB_alarm1).state;

  - platform: template
    name: "Inkbird probe 2 alarm"
    id: inkbird_IHT_2PB_alarm_state2
    icon: mdi:alarm-bell
    device_class: heat
    lambda: |-
      if (!id(inkbird_IHT_2PB_probe2).has_state()) return false;
      return id(inkbird_IHT_2PB_probe2).state >= id(inkbird_IHT_2PB_alarm2).state;

sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic

  # Template sensors updated by the BLE notification lambda below
  # probe0 = internal physical probe on the device (command 0x0D)
  # probe1 = external probe 1 / first socket (command 0x0E)
  # probe2 = external probe 2 / second socket (command 0x0F)
  - platform: template
    name: "Inkbird IHT-2PB internal probe"
    id: inkbird_IHT_2PB_probe0
    icon: mdi:thermometer
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"

  - platform: template
    name: "Inkbird IHT-2PB probe 1"
    id: inkbird_IHT_2PB_probe1
    icon: mdi:thermometer-probe
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"

  - platform: template
    name: "Inkbird IHT-2PB probe 2"
    id: inkbird_IHT_2PB_probe2
    icon: mdi:thermometer-probe
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: "temperature"
    state_class: "measurement"

  # BLE notification sensor — parses raw data and routes to probe sensors
  - platform: ble_client
    ble_client_id: inkbird_IHT_2PB_ble
    type: characteristic
    name: "Inkbird IHT-2PB last probe data"
    service_uuid: 0000ffe0-0000-1000-8000-00805f9b34fb
    characteristic_uuid: 0000ffe4-0000-1000-8000-00805f9b34fb
    notify: true
    lambda: |-
      if (x[2] != 2 && x[2] != 4 && x[2] != 6) {
        return -1.0;
      }
      uint8_t probeNr = x[2] / 2 - 1;
      float temperature;
      if (x[4] >= 254) {
        // negative
        temperature = (float) ((255 * (x[4] - 255)) + (x[5] - 255)) / 10;
      } else if (x[4] <= 11) {
        // positive
        temperature = (float) ((255 * x[4]) + x[5]) / 10;
      } else {
        return -1.0;
      }
      if (probeNr == 0) {
        id(inkbird_IHT_2PB_probe0).publish_state(temperature);
      } else if (probeNr == 1) {
        id(inkbird_IHT_2PB_probe1).publish_state(temperature);
      } else if (probeNr == 2) {
        id(inkbird_IHT_2PB_probe2).publish_state(temperature);
      }
      return (float)probeNr;

text_sensor:
  - platform: version
    name: "Firmware Version"
    entity_category: diagnostic
