esphome:
  name: testesp32c3
  friendly_name: testEsp32C3
  on_boot: #this is to avoid slow startup time because of BT and WiFi "interactions?" , check https://github.com/esphome/issues/issues/2941#issuecomment-1331851692
    priority: 250
    then:
      - wait_until:
          condition:
            wifi.connected:

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: !secret encryption_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # can lead to insufficient flash storage space
#  ap:
#    ssid: !secret wifi_fallback_ssid
#    password: !secret wifi_fallback_password

#captive_portal:

bluetooth_proxy:
  active: true
  connection_slots: 1

# uncomment to be able to track an additional ble device
#esp32_ble_tracker:
#  id: ble_tracker
#  #scan_parameters:
#  #  continuous: false
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms
#    active: true
#  max_connections: 1

packages:
  ink_bird: !include Inkbird_IHT_2PB.yaml
